spring.application.name=remind-me

spring.datasource.url=jdbc:mysql://localhost/remind_me_db?
useLegacyDatetimeCode=false&serverTimezone=UTC

spring.datasource.username=remind_me
spring.datasource.password=remind_me_pass_1!2@8$%

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false